// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-EKX_GJ5wN0AaIsSn-B-93SQ87bDTOpg',
    appId: '1:475050435412:web:7e121a6f2d38f7625b9ec1',
    messagingSenderId: '475050435412',
    projectId: 'imagesia-3f709',
    authDomain: 'imagesia-3f709.firebaseapp.com',
    storageBucket: 'imagesia-3f709.appspot.com',
    measurementId: 'G-SVV7RQH9FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxvG8mdaVmImmGGC1Il9gbgLVL1LXOf4',
    appId: '1:475050435412:android:b653787d5ffa69245b9ec1',
    messagingSenderId: '475050435412',
    projectId: 'imagesia-3f709',
    storageBucket: 'imagesia-3f709.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVIbms_QxdDKXKNXNVa6g5pKneVuMlHrA',
    appId: '1:475050435412:ios:fcd0a989e434d4565b9ec1',
    messagingSenderId: '475050435412',
    projectId: 'imagesia-3f709',
    storageBucket: 'imagesia-3f709.appspot.com',
    iosBundleId: 'com.imgaac.imagesia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVIbms_QxdDKXKNXNVa6g5pKneVuMlHrA',
    appId: '1:475050435412:ios:20600fafcd8c9ade5b9ec1',
    messagingSenderId: '475050435412',
    projectId: 'imagesia-3f709',
    storageBucket: 'imagesia-3f709.appspot.com',
    iosBundleId: 'com.example.imagesia.RunnerTests',
  );
}
